version: "1"
run:
  timeout: 5m
linters:
  enable:
    - copyloopvar
    - errorlint
    - errname
    - gocognit
    - importas
    - prealloc
    - revive
    - spancheck
    - unconvert
    - usestdlibvars
    - whitespace
linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: false
        arguments:
          - ["URL","ID","API","JSON"] # AllowList
          - ["IDFA","IDFV","AUID"] # DenyList
