// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./interface_mock.go -package=body
//

// Package body is a generated GoMock package.
package body

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// GenerateBody mocks base method.
func (m *MockStrategy) GenerateBody(params Params) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateBody", params)
	ret0, _ := ret[0].(any)
	return ret0
}

// GenerateBody indicates an expected call of GenerateBody.
func (mr *MockStrategyMockRecorder) GenerateBody(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateBody", reflect.TypeOf((*MockStrategy)(nil).GenerateBody), params)
}
