// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./interface_mock.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// GenerateTrackingURL mocks base method.
func (m *MockStrategy) GenerateTrackingURL(params Params) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTrackingURL", params)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateTrackingURL indicates an expected call of GenerateTrackingURL.
func (mr *MockStrategyMockRecorder) GenerateTrackingURL(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTrackingURL", reflect.TypeOf((*MockStrategy)(nil).GenerateTrackingURL), params)
}
