// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./interface_mock.go -package=header
//

// Package header is a generated GoMock package.
package header

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// GenerateHeaders mocks base method.
func (m *MockStrategy) GenerateHeaders(params Params) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHeaders", params)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GenerateHeaders indicates an expected call of GenerateHeaders.
func (mr *MockStrategyMockRecorder) GenerateHeaders(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHeaders", reflect.TypeOf((*MockStrategy)(nil).GenerateHeaders), params)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// getCurrentMilliTimestamp mocks base method.
func (m *MockClock) getCurrentMilliTimestamp() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getCurrentMilliTimestamp")
	ret0, _ := ret[0].(string)
	return ret0
}

// getCurrentMilliTimestamp indicates an expected call of getCurrentMilliTimestamp.
func (mr *MockClockMockRecorder) getCurrentMilliTimestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCurrentMilliTimestamp", reflect.TypeOf((*MockClock)(nil).getCurrentMilliTimestamp))
}

// getDatetimeGMT mocks base method.
func (m *MockClock) getDatetimeGMT() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getDatetimeGMT")
	ret0, _ := ret[0].(string)
	return ret0
}

// getDatetimeGMT indicates an expected call of getDatetimeGMT.
func (mr *MockClockMockRecorder) getDatetimeGMT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getDatetimeGMT", reflect.TypeOf((*MockClock)(nil).getDatetimeGMT))
}
