// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./interface_mock.go -package=unmarshaler
//

// Package unmarshaler is a generated GoMock package.
package unmarshaler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// UnmarshalResponse mocks base method.
func (m *MockStrategy) UnmarshalResponse(ctx context.Context, body []byte) ([]PartnerResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalResponse", ctx, body)
	ret0, _ := ret[0].([]PartnerResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalResponse indicates an expected call of UnmarshalResponse.
func (mr *MockStrategyMockRecorder) UnmarshalResponse(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalResponse", reflect.TypeOf((*MockStrategy)(nil).UnmarshalResponse), ctx, body)
}
